### ISSUE TITLE
Should the apex be installed to use PyProf?

### ISSUE THREAD

**Issue by aingo03304** [NVIDIA/PyProf#119]
Hello, I found the merge that implements the monkey patches for supporting the apex.

However, without the apex lib installed, I cannot execute `pyprof.init()` properly.
The error message is like this.
```
Initializing NVTX monkey patches
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aingo03304/Desktop/moco/PyProf/pyprof/nvtx/nvmarker.py", line 636, in init
    patch_apex()
  File "/home/aingo03304/Desktop/moco/PyProf/pyprof/nvtx/nvmarker.py", line 388, in patch_apex
    patch_apex_pyt()
  File "/home/aingo03304/Desktop/moco/PyProf/pyprof/nvtx/nvmarker.py", line 425, in patch_apex_pyt
    patch_apex_module("apex.amp")
  File "/home/aingo03304/Desktop/moco/PyProf/pyprof/nvtx/nvmarker.py", line 457, in patch_apex_module
    if importlib.util.find_spec(modstr) is not None:
  File "/home/aingo03304/opt/python-3.6.10/lib/python3.6/importlib/util.py", line 88, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
ModuleNotFoundError: No module named 'apex'
```

Then, I found line 457 pyprof/nvtx/nvmarker.py says
```python
# modstr can be apex.amp
def patch_apex_module(modstr):
    """
    Patch all forward/backward/step functions in classes in the given apex module.
    """
    if importlib.util.find_spec(modstr) is not None:     # This branch throws error when apex is not installed.
        mod = importlib.import_module(modstr)

        for n, v in ins.getmembers(mod):
            # This makes sure we don't patch random other modules that are imported by the target module
            #
            if is_same_module_or_submodule(mod, ins.getmodule(v)):
                if (ins.isclass(v)):
                    patch_apex_class(v)
```
Because `importlib.util.find_spec` should import `apex` first, and try to find apex.amp, apex lib should be installed to execute `pyprof.init()`.

This can be a serious issue so that you should change the CI env and/or test suites.

**Comment by adityaiitb** [comment]
Has this been fixed? Can we close this? @debermudez
