### ISSUE TITLE
Crash in OneZero KeyError: 'shape'

### ISSUE THREAD

**Issue by jeremysalwen** [NVIDIA/PyProf#139]
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jeremy/PycharmProjects/hearthstone_battlegrounds/venv/lib/python3.7/site-packages/pyprof/prof/__main__.py", line 21, in <module>
    main()
  File "/home/jeremy/PycharmProjects/hearthstone_battlegrounds/venv/lib/python3.7/site-packages/pyprof/prof/prof.py", line 253, in main
    xx = foo(mod, op, d)
  File "/home/jeremy/PycharmProjects/hearthstone_battlegrounds/venv/lib/python3.7/site-packages/pyprof/prof/prof.py", line 169, in foo
    xx = OneZero(d)
  File "/home/jeremy/PycharmProjects/hearthstone_battlegrounds/venv/lib/python3.7/site-packages/pyprof/prof/memory.py", line 42, in __init__
    self.input = Tensor(arg['shape'], arg['dtype'])
KeyError: 'shape'
```

From version r20.12.

happened when profiling https://github.com/JDBumgardner/stone_ground_hearth_battles/blob/master/hearthstone/training/pytorch/ppo.py

**Comment by adityaiitb** [comment]
Thanks for reporting the issue. Can you please share the input `dict` file.

**Comment by jeremysalwen** [comment]
Uploaded it to google drive: https://drive.google.com/file/d/1AoRMK3mKXlJV-tccnyrkLL0Qv9TVVzvM/view?usp=sharing

**Comment by adityaiitb** [comment]
Identified two issues
- Tensor.log_softmax (fixed in https://github.com/NVIDIA/PyProf/pull/140) 
- torch.zeros

Working on the second issue.

**Comment by adityaiitb** [comment]
Fixed the second issue in https://github.com/NVIDIA/PyProf/pull/141. The pull requests should be in soon.
Thanks for using the tool and reporting issues.

**Comment by jeremysalwen** [comment]
Thank you, those fixes worked for me!
