### ISSUE TITLE
No module named 'fast_self_multihead_attn'

### ISSUE THREAD

**Issue by II245** [NVIDIA/PyProf#167]
Hello! 
Found ModuleNotFoundError when I use pyprof with apex.

To reproduce:

```python
import pyprof
pyprof.nvtx.init()
```

```
Traceback (most recent call last):
  File "/home/*/work/convasr/repro.py", line 4, in <module>
    pyprof.nvtx.init()
  File "/opt/conda/lib/python3.8/site-packages/pyprof/nvtx/nvmarker.py", line 403, in init
    patch_apex()
  File "/opt/conda/lib/python3.8/site-packages/pyprof/nvtx/nvmarker.py", line 306, in patch_apex
    patch_apex_pyt()
  File "/opt/conda/lib/python3.8/site-packages/pyprof/nvtx/nvmarker.py", line 345, in patch_apex_pyt
    patch_apex_module("apex.contrib.multihead_attn")
  File "/opt/conda/lib/python3.8/site-packages/pyprof/nvtx/nvmarker.py", line 376, in patch_apex_module
    mod = importlib.import_module(modstr)
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.8/site-packages/apex/contrib/multihead_attn/__init__.py", line 1, in <module>
    from .self_multihead_attn import SelfMultiheadAttn
  File "/opt/conda/lib/python3.8/site-packages/apex/contrib/multihead_attn/self_multihead_attn.py", line 9, in <module>
    from .fast_self_multihead_attn_func          import fast_self_attn_func
  File "/opt/conda/lib/python3.8/site-packages/apex/contrib/multihead_attn/fast_self_multihead_attn_func.py", line 2, in <module>
    import fast_self_multihead_attn
ModuleNotFoundError: No module named 'fast_self_multihead_attn'
```

Everything works well with this workaround:
```python
import pyprof
pyprof.nvtx.nvmarker.patch_apex_module = lambda modstr, old = pyprof.nvtx.nvmarker.patch_apex_module: old(modstr) if modstr != 'apex.contrib.multihead_attn' else None  # coused by this bug https://github.com/NVIDIA/apex/issues/958
pyprof.nvtx.init()
```

**Comment by II245** [comment]
@adityaiitb Thanks for the reply, I can't find the issue tab in the repo from your link. Could you please show where to place bug description?

**Comment by adityaiitb** [comment]
Just enabled the issues tab. For some reason it was not enabled by default.
