### ISSUE TITLE
assertion fired

### ISSUE THREAD

**Issue by ethem-kinginthenorth** [NVIDIA/PyProf#67]
406 fprop   0 na                              modern::vectorized_elementwise_kernel           na=na,                                                3072
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/ecan/PyProf/pyprof/prof/__main__.py", line 21, in <module>
    main()
  File "/ecan/PyProf/pyprof/prof/prof.py", line 242, in main
    xx = foo(mod, op, d)
  File "/ecan/PyProf/pyprof/prof/prof.py", line 74, in foo
    xx = Linear(d)
  File "/ecan/PyProf/pyprof/prof/linear.py", line 115, in __init__
    assert any(x in d.name for x in Linear.biasKernels), f"Kernel name: {d.name}"
AssertionError: Kernel name: softmax_warp_backward

**Comment by adityaiitb** [comment]
Are you using PyTorch 1.6 or NV docker 20.06 or higher? This is related to https://github.com/NVIDIA/PyProf/issues/46. We are working on it. There are two temporary solutions:
a) Fall back to PyTorch 1.5 / NV docker 20.03.
b) Use the latest PyTorch nightly (might require building).

The fix is [here](https://github.com/pytorch/pytorch/pull/42565).

**Comment by ethem-kinginthenorth** [comment]
@adityaiitb thanks. I am on a100 and using nvidia docker. So none of those options seem feasible for me. Anyways thanks. I am closing this issue as there is not much to do.
